#!/usr/bin/env bash
# Check if all required parameters are passed
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Transfer file to server
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
