#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx

# Configure nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Hello-World \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
kill -QUIT "$(cat /run/nginx.pid)"

# Test nginx configuration
nginx -t
