#!/usr/bin/env bash
# Prints "Best School" 10 times using while loop
# and on the ninth iteration, prints "Hi"

n=0

while [ "$n" -lt 10 ]; do
  echo "Best School"
  
  # if statement to print Hi when n is 9
  if [ "$n" -eq 9 ]; then
    echo "Hi"
  fi

  ((n++))
done
