#!/usr/bin/env bash
# cultures with numbers ...

n=1

while [ "$n" -lt 20 ]; do
  
  case "$n" in
    4)
      echo "$n"
      echo "bad luck from China"
      ;;
    9)
      echo "$n"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$n"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$n"
      ;;
  esac

  ((n++))
done
